[package]
name = "chunker-cli"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = "4.5"
colored = "2.1"
indicatif = "0.17"
tokio = { version = "1.41", features = ["full"] }

[dev-dependencies]
tempfile = "3.14"